name: flutter_layout
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^1.0.4
  banner_view: ^1.1.2
  event_bus: ^1.0.1
  fluttertoast: ^2.0.7
  chewie: ^0.7.0
  shared_preferences: ^0.4.2
  flutter_plugin_webview: ^0.0.13
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
          - images/tx.jpg
          - images/chakan.png
          - images/chakan1.png
          - images/sw.jpg
          - images/ic_nav_news_normal.png
          - images/ic_nav_news_actived.png
          - images/ic_nav_tweet_normal.png
          - images/ic_nav_tweet_actived.png
          - images/ic_nav_discover_normal.png
          - images/ic_nav_discover_actived.png
          - images/ic_nav_my_normal.png
          - images/ic_nav_my_pressed.png
          - images/da.jpg
          - images/DVa.jpg
          - images/lk.jpg
          - images/ts.jpg
          - images/t.jpg
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
